<?php
// $Id: xoops_version.php,v 1.11 2006/03/31 23:51:20 andrew Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //


// Any copyright notice, instructions, etc...
$modversion['name'] = _MI_EVENTS_NAME;
$modversion['version'] = 0.22;
$modversion['description'] = _MI_EVENTS_DESC;
$modversion['credits'] = '';
$modversion['author'] = 'Andrew Mills';
$modversion['help'] = 'help.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'modulelogo.png';
$modversion['dirname'] = 'amevents';

// Admin
$modversion['hasAdmin']  = 1;
$modversion['adminindex']	= "admin/index.php";
$modversion['adminmenu']	= "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;
// only show if users are allowed to submit articles
global $xoopsModule, $xoopsModuleConfig;
if(isset($xoopsModuleConfig['allowusersubmit']) && $xoopsModuleConfig['allowusersubmit'] == 1) {
	$modversion['sub'][1]['name'] = _MI_EVENTS_SMNAME1;
	$modversion['sub'][1]['url']  = "submit.php";
}


// Templates
$modversion['templates'][1]['file'] 		= 'event_index.html'; // main index
$modversion['templates'][1]['description'] 	= '';
$modversion['templates'][2]['file']			= 'event_item.html'; // view article
$modversion['templates'][2]['description'] 	= '';
$modversion['templates'][3]['file']			= 'event_submit.html'; // view article
$modversion['templates'][3]['description'] 	= '';
$modversion['templates'][4]['file'] 		= 'event_indexday.html'; // main index
$modversion['templates'][4]['description'] 	= '';
$modversion['templates'][5]['file']			= 'event_submitted.html'; // 
$modversion['templates'][5]['description'] 	= '';
$modversion['templates'][6]['file']			= 'event_email.html'; // 
$modversion['templates'][6]['description'] 	= '';


// Blocks
$modversion['blocks'][1]['file']         = "events_upcoming.php";
$modversion['blocks'][1]['name']         = _MI_EVENTS_BNAME1;
$modversion['blocks'][1]['description']  = "Shows upcoming events";
$modversion['blocks'][1]['show_func']    = "events_upcoming_show";
$modversion['blocks'][1]['edit_func']    = "events_upcoming_edit";
$modversion['blocks'][1]['options']      = "5|20|j M Y|";
$modversion['blocks'][1]['template']     = "events_block_upcoming.html";

$modversion['blocks'][2]['file']         = "events_calendar.php";
$modversion['blocks'][2]['name']         = _MI_EVENTS_BNAME2;
$modversion['blocks'][2]['description']  = "Shows event calendar";
$modversion['blocks'][2]['show_func']    = "events_calendar_show";
$modversion['blocks'][2]['edit_func']    = "events_calendar_edit";
$modversion['blocks'][2]['options']      = "1|15|"; // enable dhtml|dhtml title length
$modversion['blocks'][2]['template']     = "events_block_calendar.html";


// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql']		= "sql/mysql.sql";
//$modversion['sqlfile']['postgresql']	= "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0]	= "amevents_country";
$modversion['tables'][1]	= "amevents_events";
//$modversion['tables'][2]	= "amevents_prefs";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "amevents_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'id';
$modversion['comments']['pageName'] = 'index.php';

// Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'amevents_notify_iteminfo';

// Admin related
$modversion['notification']['category'][1]['name']				= 'admin';
$modversion['notification']['category'][1]['title']				= _MI_AMEVENT_EVENTADMIN_NOTIFY;
$modversion['notification']['category'][1]['description']		= _MI_AMEVENT_EVENTADMIN_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from']	= 'index.php';

// Global stuff
$modversion['notification']['category'][2]['name']				= 'global';
$modversion['notification']['category'][2]['title']				= _MI_AMEVENT_EVENT_NOTIFY;
$modversion['notification']['category'][2]['description']		= _MI_AMEVENT_EVENT_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from']	= 'index.php';

// Notify admin of user subbed event for validation
$modversion['notification']['event'][1]['name']				= 'new_eventadmin';
$modversion['notification']['event'][1]['category']			= 'admin';
$modversion['notification']['event'][1]['title']			= _MI_AMEVENT_NEWUSEREVENT_NOTIFY;
$modversion['notification']['event'][1]['caption']			= _MI_AMEVENT_NEWUSEREVENT_NOTIFYCAP;
$modversion['notification']['event'][1]['description']		= _MI_AMEVENT_NEWUSEREVENT_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template']	= 'event_neweventadmin_notify';
$modversion['notification']['event'][1]['mail_subject']		= _MI_AMEVENT_NEWUSEREVENT_NOTIFYSBJ;
$modversion['notification']['event'][1]['admin_only']		= 1;

// Notify admin of user subbed event for validation
$modversion['notification']['event'][2]['name']				= 'new_eventadmin_auto';
$modversion['notification']['event'][2]['category']			= 'admin';
$modversion['notification']['event'][2]['title']			= _MI_AMEVENT_NEWUSEREVENT_NOTA;
$modversion['notification']['event'][2]['caption']			= _MI_AMEVENT_NEWUSEREVENT_NOTCAPA;
$modversion['notification']['event'][2]['description']		= _MI_AMEVENT_NEWUSEREVENT_NOTDSCA;
$modversion['notification']['event'][2]['mail_template']	= 'event_neweventadmin_notifya';
$modversion['notification']['event'][2]['mail_subject']		= _MI_AMEVENT_NEWUSEREVENT_NOTSBJA;
$modversion['notification']['event'][2]['admin_only']		= 1;

// Notify users
$modversion['notification']['event'][3]['name']				= 'new_eventuser';
$modversion['notification']['event'][3]['category']			= 'global';
$modversion['notification']['event'][3]['title']			= _MI_AMEVENT_NEWEVENT_NOTIFY;
$modversion['notification']['event'][3]['caption']			= _MI_AMEVENT_NEWEVENT_NOTIFYCAP;
$modversion['notification']['event'][3]['description']		= _MI_AMEVENT_NEWEVENT_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template']	= 'event_neweventuser_notify';
$modversion['notification']['event'][3]['mail_subject']		= _MI_AMEVENT_NEWEVENT_NOTIFYSBJ;


// Config options
// 

// Date format for main index listings
$modversion['config'][2]['name']		= 'datefrmt';
$modversion['config'][2]['title']		= '_MI_AMEVENT_OPTION_DATE';
$modversion['config'][2]['description']	= '_MI_AMEVENT_OPTION_DATEDSC';
$modversion['config'][2]['formtype']	= 'textbox';
$modversion['config'][2]['valuetype']	= 'text';
$modversion['config'][2]['default']		= 'd/m/Y';

// Date format for event page
$modversion['config'][3]['name']		= 'datefrmtmain';
$modversion['config'][3]['title']		= '_MI_AMEVENT_OPTION_DATEMAIN';
$modversion['config'][3]['description']	= '_MI_AMEVENT_OPTION_DATEMAINDSC';
$modversion['config'][3]['formtype']	= 'textbox';
$modversion['config'][3]['valuetype']	= 'text';
$modversion['config'][3]['default']		= 'jS M Y';

// Date format for admin
$modversion['config'][4]['name']		= 'datefrmtadmin';
$modversion['config'][4]['title']		= '_MI_AMEVENT_OPTION_DATEADMIN';
$modversion['config'][4]['description']	= '_MI_AMEVENT_OPTION_DATEADMINDSC';
$modversion['config'][4]['formtype']	= 'textbox';
$modversion['config'][4]['valuetype']	= 'text';
$modversion['config'][4]['default']		= 'Y-m-d';

// allowprintversion
$modversion['config'][5]['name']		= 'allowprintversion';
$modversion['config'][5]['title']		= '_MI_AMEVENT_OPT_PRINTVER';
$modversion['config'][5]['description']	= '_MI_AMEVENT_OPT_PRINTVERDSC';
$modversion['config'][5]['formtype']	= 'yesno';
$modversion['config'][5]['valuetype']	= 'int';
$modversion['config'][5]['default']		= 1;

// Enable e-mail to friend feature allowemailtofriend
$modversion['config'][6]['name']		= 'allowemailtofriend';
$modversion['config'][6]['title']		= '_MI_AMEVENT_OPT_EML2FRE';
$modversion['config'][6]['description']	= '_MI_AMEVENT_OPT_EML2FREDSC';
$modversion['config'][6]['formtype']	= 'yesno';
$modversion['config'][6]['valuetype']	= 'int';
$modversion['config'][6]['default']		= 0;

// Log in to use - emailtofriendlogin
$modversion['config'][7]['name']		= 'emailtofriendlogin';
$modversion['config'][7]['title']		= '_MI_AMEVENT_OPT_EMLLOGGEDIN';
$modversion['config'][7]['description']	= '_MI_AMEVENT_OPT_EMLLOGGEDINDSC';
$modversion['config'][7]['formtype']	= 'yesno';
$modversion['config'][7]['valuetype']	= 'int';
$modversion['config'][7]['default']		= 1;

// emailtofriendownmsg
$modversion['config'][8]['name']		= 'emailtofriendownmsg';
$modversion['config'][8]['title']		= '_MI_AMEVENT_OPT_EMLOWNMSG';
$modversion['config'][8]['description']	= '_MI_AMEVENT_OPT_EMLOWNMSGDSC';
$modversion['config'][8]['formtype']	= 'yesno';
$modversion['config'][8]['valuetype']	= 'int';
$modversion['config'][8]['default']		= 1;

// emailtofreindchars
$modversion['config'][9]['name']		= 'emailtofreindchars';
$modversion['config'][9]['title']		= '_MI_AMEVENT_OPT_EMLCHARS';
$modversion['config'][9]['description']	= '_MI_AMEVENT_OPT_EMLCHARSDSC';
$modversion['config'][9]['formtype']	= 'textbox';
$modversion['config'][9]['valuetype']	= 'int';
$modversion['config'][9]['default']		= '200';

// Subject text 
$modversion['config'][10]['name']			= 'emailtofreindsubect';
$modversion['config'][10]['title']			= '_MI_AMEVENT_OPT_EMLMSGSBJCT';
$modversion['config'][10]['description']	= '_MI_AMEVENT_OPT_EMLMSGSBJCTDSC';
$modversion['config'][10]['formtype']		= 'textbox';
$modversion['config'][10]['valuetype']		= 'text';
$modversion['config'][10]['default']		= _MI_AMEVENT_OPT_EMLMSGSUBJECT; 

// send to friend e-mail text
$modversion['config'][11]['name']			= 'emailtext';
$modversion['config'][11]['title']			= '_MI_AMEVENT_OPT_EMAILTXT';
$modversion['config'][11]['description']	= '_MI_AMEVENT_OPT_EMAILTXTSC';
$modversion['config'][11]['formtype']		= 'textarea';
$modversion['config'][11]['valuetype']		= 'text';
$modversion['config'][11]['default']		= _MI_AMEVENT_OPT_EMAILTXTMSG;


// Show article title in page title
$modversion['config'][12]['name']			= 'titleaspagetitle';
$modversion['config'][12]['title']			= '_MI_AMEVENT_OPTION_PAGETTL';
$modversion['config'][12]['description']	= '_MI_AMEVENT_OPTION_PAGETTLDSC';
$modversion['config'][12]['formtype']		= 'select';
$modversion['config'][12]['valuetype']		= 'int';
$modversion['config'][12]['default']		= '1';
$modversion['config'][12]['options']		= array('_MI_AMEVENT_OPTION_PAGETTL1' => '0', '_MI_AMEVENT_OPTION_PAGETTL2' => '1', '_MI_AMEVENT_OPTION_PAGETTL3' => '2');

// default admin editor
$modversion['config'][13]['name']			= 'articleeditadmin';
$modversion['config'][13]['title']			= '_MI_AMEVENT_OPT_EDITADMIN';
$modversion['config'][13]['description']	= '_MI_AMEVENT_OPT_EDITADMINDSC';
$modversion['config'][13]['formtype']		= 'select';
$modversion['config'][13]['valuetype']		= 'int';
$modversion['config'][13]['default']		= '0';
$modversion['config'][13]['options']		= array('XOOPS dhtml' => '0', 'SPAW' => '1', 'FCK Editor' => '2', 'HTML Area' => '3', 'Koivi' => '4', 'XOOPS Compact' => '5');

// user (visitor) editor
$modversion['config'][14]['name']			= 'articleedituser';
$modversion['config'][14]['title']			= '_MI_AMEVENT_OPT_EDITUSER';
$modversion['config'][14]['description']	= '_MI_AMEVENT_OPT_EDITUSERDSC';
$modversion['config'][14]['formtype']		= 'select';
$modversion['config'][14]['valuetype']		= 'int';
$modversion['config'][14]['default']		= '0';
$modversion['config'][14]['options']		= array('XOOPS dhtml' => '0', 'SPAW' => '1', 'FCK Editor' => '2', 'HTML Area' => '3', 'Koivi' => '4', 'XOOPS Compact' => '5');

// User logged in to submit
$modversion['config'][15]['name']			= 'loggedin';
$modversion['config'][15]['title']			= '_MI_AMEVENT_OPTION_LOGGEDIN';
$modversion['config'][15]['description']	= '_MI_AMEVENT_OPTION_LOGGEDINDSC';
$modversion['config'][15]['formtype']		= 'yesno';
$modversion['config'][15]['valuetype']		= 'int';
$modversion['config'][15]['default']		= 1;

// User allowed to submit
$modversion['config'][16]['name']			= 'allowusersubmit';
$modversion['config'][16]['title']			= '_MI_AMEVENT_OPT_ALLOWSUB';
$modversion['config'][16]['description']	= '_MI_AMEVENT_OPT_ALLOWSUBDSC';
$modversion['config'][16]['formtype']		= 'yesno';
$modversion['config'][16]['valuetype']		= 'int';
$modversion['config'][16]['default']		= 1;

// Auto validate user submitted events
$modversion['config'][17]['name']			= 'autosubmit';
$modversion['config'][17]['title']			= '_MI_AMEVENT_OPT_AUTOSUB';
$modversion['config'][17]['description']	= '_MI_AMEVENT_OPT_AUTOSUBDSC';
$modversion['config'][17]['formtype']		= 'yesno';
$modversion['config'][17]['valuetype']		= 'int';
$modversion['config'][17]['default']		= 0;

// Do not expire events from view on user listing.
$modversion['config'][20]['name']			= 'noexpire';
$modversion['config'][20]['title']			= '_MI_AMEVENT_OPT_NOEXPIRE';
$modversion['config'][20]['description']	= '_MI_AMEVENT_OPT_NOEXPIREDSC';
$modversion['config'][20]['formtype']		= 'yesno';
$modversion['config'][20]['valuetype']		= 'int';
$modversion['config'][20]['default']		= 0;

// Show duration - default yes (NOT YET IMPLEMENTED)
//$modversion['config'][21]['name']			= 'noduration';
//$modversion['config'][21]['title']			= '_MI_AMEVENT_OPT_NOEXPIRE';
//$modversion['config'][21]['description']	= '_MI_AMEVENT_OPT_NOEXPIREDSC';
//$modversion['config'][21]['formtype']		= 'yesno';
//$modversion['config'][21]['valuetype']		= 'int';
//$modversion['config'][21]['default']		= 1;

// Show location - default yes (NOT YET IMPLEMENTED)
//$modversion['config'][22]['name']			= 'nolocation';
//$modversion['config'][22]['title']			= '_MI_AMEVENT_OPT_NOEXPIRE';
//$modversion['config'][22]['description']	= '_MI_AMEVENT_OPT_NOEXPIREDSC';
//$modversion['config'][22]['formtype']		= 'yesno';
//$modversion['config'][22]['valuetype']		= 'int';
//$modversion['config'][22]['default']		= 1;


?>
