Hello {X_UNAME},

A new event has been added on {X_SITENAME}
and can be viewed at:

{AMEVENT_URL}

You can unsubscribe from events generated by the
{X_MODULE} module by going to:

{X_UNSUBSCRIBE_URL}

-- 
 {X_SITENAME} - {X_SITEURL}
 {X_ADMINMAIL}
